# Javascript

## try..catch

Lorsque nous avons un problème dans notre code celui-ci s'arrête immédiatement, nous pouvons faire un console.log pour voir ou est le problème, mais peut-on faire en sorte que si un problème est détecté dans une partie du code, au lieu de s'arrêter immédiatement, il exécute quelque chose d'autre ? la réponse est oui ! ... il suffit d'utiliser `try... catch`

Voici la syntaxe :
```js
try{
    // Mettez votre code ici
}catch(err){
    // gestion de l'erreur ici
}
```

